Create Main-de.strings
rampatra/presentify-localization pull request #2
Opened 2020-06-15 20:05 UTC by Luca1719

Localized by Luca (for reference: Reddit: u/Luca1719)

2020-06-15 21:53 UTC, zeisss commented on Main-de.string
> +"rij-ew-yIo.title" = "Linienbreite verringern";
Here you translated the same string (Line weight) differently. I think "Liniendicke" is the better word.

2020-06-15 22:14 UTC, rampatra commented
Thanks a lot @Luca1719 and @zeisss for the help.

Just one minor thing before I merge this. The file name should be `Main.strings` and `Localizable.strings` and should be inside `de.lproj` folder.

2020-06-16 16:38 UTC, rampatra commented
I am thinking it would be better for me to reorganize the files in your fork and then merge them. Hope that's okay.

2020-07-03 11:34 UTC, Suplanus requested changes

2020-07-03 11:34 UTC, Suplanus commented on Main-de.string
> +"H6d-jK-d3o.title" = "Halte die Option-Taste während du Rechtecke und Kreise malst, um sie mit einer halbtransparenten Farbe zu füllen.";
Better:
"Halte die Option-Taste während Du Rechtecke oder Kreise malst, um sie mit einer halbtransparenten Farbe zu füllen."

2020-07-03 11:34 UTC, Suplanus commented on Main-de.string
> +"IAo-SY-fd9.title" = "Öffne ...";
Better:
"Öffnen..."

2020-07-03 11:34 UTC, Suplanus commented on Main-de.string
> +"J5U-5w-g23.title" = "Justieren";
Better:
"Ausrichten"

2020-07-03 11:34 UTC, Suplanus commented on Main-de.string
> +"JvL-1K-hfp.ibShadowedToolTip" = "Kommentarkontrollen bearbeiten";
Better:
"Markier-Steuerelemente verschieben"

2020-07-03 11:34 UTC, Suplanus commented on Main-de.string
> +"LE2-aR-0XJ.title" = "Alle nach vorne bringen";
Better:
"Alle nach vorne bringen"

2020-07-03 11:34 UTC, Suplanus commented on Main-de.string
> +"RIq-pW-x2s.title" = "Setze das Schriftgewicht deiner Kommentare";
Better:
"Setze die breite der Markierungen"

2020-07-03 11:34 UTC, Suplanus commented on Main-de.string
> +"S0p-oC-mLd.title" = "Zuw Auswahl springen";
"Zur Auswahl springen"

2020-07-03 11:34 UTC, Suplanus commented on Main-de.string
> +"TOY-jq-L3N.title" = "Favoritfarbe";
"Favorisierte Farben"

2020-07-03 11:34 UTC, Suplanus commented on Main-de.string
> +"Vjx-xi-njq.title" = "Kursic";
"Kursiv"

2020-07-03 11:34 UTC, Suplanus commented on Main-de.string
> +"YEy-JH-Tfz.title" = "Finden und ersetzen ...";
"Suchen und ersetzen..."

2020-07-03 11:34 UTC, Suplanus commented on Main-de.string
> +"cMw-Qt-4pz.title" = "Presentify starten, wenn du deinen Mac startest";
"Presentify starten, wenn dein Mac startet"

2020-07-03 11:34 UTC, Suplanus commented on Main-de.string
> +/* Class = "NSMenuItem"; title = "Kern"; ObjectID = "jBQ-r6-VK2"; */
What means "Kern" in english?

2020-07-03 11:34 UTC, Suplanus commented on Main-de.string
> +"mXB-PS-wv2.title" = "Beim App-Launch Mauszeiger markieren";
"Beim Programmstart Mauszeiger markieren"

2020-07-03 11:34 UTC, Suplanus commented on Main-de.string
> +"vli-ph-UGB.title" = "Erste favorisierte Farve";
"Erste favorisierte Farbe"

2020-07-03 11:34 UTC, Suplanus commented on Main-de.string
> +"6fu-rC-JLd.title" = "Mit Berührung zeichen";
"Mit Touch zeichnen"

2020-07-12 13:15 UTC, merged

2020-07-12 13:20 UTC, rampatra commented
If someone else can please corroborate on the comments made by @Suplanus and @zeisss then I can make the changes.

2020-07-12 14:52 UTC, rampatra commented
@zeisss Also, I have given a free license of Presentify to @Luca1719 and @Suplanus so if you need one then please let me know. Would be happy to share one.

Thanks a lot for your help 🙏

2020-07-13 13:27 UTC, zeisss commented
No problem. No need to a license. Happy to help.